[package]
name = "lumen"
version = "0.1.0"
edition = "2021"

authors = ["Omar Palomares Velasco <trixxo@corp>"]
description = "LÚMEN: lenguaje educativo rápido, simple y cercano a la máquina"
license = "MIT"
repository = "https://github.com/TriXxoCorp/lumen"
readme = "README.md"

[dependencies]
